### PR TITLE
Bump Smack dependency from 4.4.7 to 4.5.0-alpha4-SNAPSHOT

### PR DESCRIPTION
**Pull request by guusdk**
Pull in latest changes from Smack (that includes Tagging and rework of existing tests.

This introduces a SNAPSHOT dependency, which should be replaced with a proper release (that's not available yet at the time that this commit was made).

### CODE REVIEW

**Comment by guusdk** [comment]
Unexpected test failures that aren't reproduced locally. Marked the PR as 'draft' while figuring out what's going on.

**Comment by guusdk** [comment]
The problem is likely resolved by https://github.com/igniterealtime/Smack/pull/586 which will hopefully become part of Smack 4.5.0-alpha4-SNAPSHOT

**Comment by guusdk** [comment]
Coincidentally, Smack had just released 4.5.0-alpha3 while I was drafting this PR. As we want a change in Smack that hasn't made it into that release, I've updated this PR to use 4.5.0-alpha4-SNAPSHOT

**Comment by guusdk** [comment]
4.5.0-alpha4-SNAPSHOT is now available, making the checks in this PR go green. \o/

**Review by Fishbowler — APPROVED** [review]

**Pull request merged**
